apiVersion: v1
data:
  mongooseim.toml: |
    [general]
      loglevel = "warning"
      hosts = ["xmpp-mongo.wingtrill.com"]
      host_types = []
      default_server_domain = "xmpp-mongo.wingtrill.com"
      registration_timeout = "infinity"
      language = "en"

    [[listen.http]]
      port = 5280
      transport.num_acceptors = 10
      transport.max_connections = 1024

      [[listen.http.handlers.mongoose_bosh_handler]]
        host = "_"
        path = "/http-bind"

      [[listen.http.handlers.mongoose_websocket_handler]]
        host = "_"
        path = "/ws-xmpp"

    [[listen.http]]
      port = 5285
      transport.num_acceptors = 10
      transport.max_connections = 1024
      tls.verify_mode = "none"
      tls.certfile = "priv/ssl/fake_cert.pem"
      tls.keyfile = "priv/ssl/fake_key.pem"

      [[listen.http.handlers.mongoose_bosh_handler]]
        host = "_"
        path = "/http-bind"

      [[listen.http.handlers.mongoose_websocket_handler]]
        host = "_"
        path = "/ws-xmpp"

    [[listen.http]]
      ip_address = "127.0.0.1"
      port = 5551
      transport.num_acceptors = 10
      transport.max_connections = 1024

      [[listen.http.handlers.mongoose_graphql_handler]]
        host = "localhost"
        path = "/api/graphql"
        schema_endpoint = "admin"
        username = "admin"
        password = "secret"

    [[listen.http]]
      ip_address = "0.0.0.0"
      port = 5541
      transport.num_acceptors = 10
      transport.max_connections = 1024

      [[listen.http.handlers.mongoose_graphql_handler]]
        host = "_"
        path = "/api/graphql"
        schema_endpoint = "domain_admin"

    [[listen.http]]
      ip_address = "0.0.0.0"
      port = 5561
      transport.num_acceptors = 10
      transport.max_connections = 1024

      [[listen.http.handlers.mongoose_graphql_handler]]
        host = "_"
        path = "/api/graphql"
        schema_endpoint = "user"

    [[listen.http]]
      port = 9091
      transport.num_acceptors = 10

      [[listen.http.handlers.mongoose_prometheus_handler]]
        host = "_"
        path = "/metrics"

    [[listen.c2s]]
      port = 5222
      access = "c2s"
      shaper = "normal"
      max_stanza_size = 65536
      tls.verify_mode = "none"
      tls.certfile = "priv/ssl/fake_cert.pem"
      tls.keyfile = "priv/ssl/fake_key.pem"

    [[listen.s2s]]
      port = 5269
      shaper = "fast"
      max_stanza_size = 131072
      tls.verify_mode = "none"
      tls.certfile = "priv/ssl/fake_cert.pem"
      tls.keyfile = "priv/ssl/fake_key.pem"

    [[listen.component]]
      port = 8888
      access = "all"
      shaper = "fast"
      ip_address = "127.0.0.1"
      password = "secret"

    [auth]

      # methods
      [auth.internal]

    [internal_databases.mnesia]

    [outgoing_pools.rdbms.default]
      scope = "global"
      workers = 5

      [outgoing_pools.rdbms.default.connection]
        driver = "mysql"
        host = "127.0.0.1"
        port = 3306
        database = "mongooseim"
        username = "mongooseim"
        password = "mongooseim"

    [outgoing_pools.redis.global_distrib]
      scope = "global"
      workers = 10

      [outgoing_pools.redis.global_distrib.connection]
        host = "127.0.0.1"
        port = 6379

    [services.service_bosh]

    [services.service_mongoose_system_metrics]

    [modules.mod_adhoc]

    [modules.mod_disco]
      users_can_see_hidden_services = false

    [modules.mod_stream_management]

    [modules.mod_register]
      ip_access = [
        {address = "127.0.0.0/8", policy = "allow"},
        {address = "0.0.0.0/0", policy = "deny"}
      ]
      access = "register"

    [modules.mod_presence]

    [modules.mod_sic]

    [modules.mod_vcard]
      host = "vjud.@HOST@"

    [modules.mod_carboncopy]

    [modules.mod_last]
      backend = "rdbms"

    [modules.mod_roster]
      backend = "rdbms"

    [modules.mod_offline]
      access_max_user_messages = "max_user_offline_messages"

    [modules.mod_mam]
      backend = "rdbms"

      [modules.mod_mam.pm]
        archive_groupchats = false

      [modules.mod_mam.muc]
        host = "muc.xmpp-mongo.wingtrill.com"

    [modules.mod_inbox]
      backend = "rdbms"
      reset_markers = ["displayed"]
      groupchat = ["muc_light"]

    [modules.mod_smart_markers]
      backend = "rdbms"

    [modules.mod_muc_light]
      backend = "rdbms"
      host = "muc.xmpp-mongo.wingtrill.com"

    [modules.mod_muc]
      host = "muc.xmpp-mongo.wingtrill.com"
      access = "muc"
      access_create = "muc_create"
      access_admin = "muc_admin"

    [instrumentation.prometheus]

    [instrumentation.log]

    [shaper.normal]
      max_rate = 16_384

    [shaper.fast]
      max_rate = 50_000

    [shaper.mam_shaper]
      max_rate = 1

    [shaper.mam_global_shaper]
      max_rate = 1000

    [acl]
      local = [{}]

    [access]
      max_user_sessions = [
        {acl = "all", value = 1000}
      ]

      max_user_offline_messages = [
        {acl = "admin", value = 5000},
        {acl = "all", value = 100}
      ]

      local = [
        {acl = "local", value = "allow"}
      ]

      c2s = [
        {acl = "blocked", value = "deny"},
        {acl = "all", value = "allow"}
      ]

      muc_admin = [
        {acl = "admin", value = "allow"}
      ]

      muc_create = [
        {acl = "local", value = "allow"}
      ]

      muc = [
        {acl = "all", value = "allow"}
      ]

      register = [
        {acl = "all", value = "allow"}
      ]

      mam_set_prefs = [
        {acl = "all", value = "default"}
      ]

      mam_get_prefs = [
        {acl = "all", value = "default"}
      ]

      mam_lookup_messages = [
        {acl = "all", value = "default"}
      ]

      mam_set_prefs_shaper = [
        {acl = "all", value = "mam_shaper"}
      ]

      mam_get_prefs_shaper = [
        {acl = "all", value = "mam_shaper"}
      ]

      mam_lookup_messages_shaper = [
        {acl = "all", value = "mam_shaper"}
      ]

      mam_set_prefs_global_shaper = [
        {acl = "all", value = "mam_global_shaper"}
      ]

      mam_get_prefs_global_shaper = [
        {acl = "all", value = "mam_global_shaper"}
      ]

      mam_lookup_messages_global_shaper = [
        {acl = "all", value = "mam_global_shaper"}
      ]

    [s2s]
      default_policy = "deny"

      [s2s.outgoing]
        port = 5269
        tls.mode = "starttls"
        tls.verify_mode = "none"
        tls.certfile = "priv/ssl/fake_cert.pem"
        tls.keyfile = "priv/ssl/fake_key.pem"
kind: ConfigMap
metadata:
  name: mongooseim-config
  namespace: mim
