apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongooseim.fullname" . }}-mysql
  labels:
    {{- include "mongooseim.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  selector:
    {{- include "mongooseim.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
