{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongooseim.fullname" . }}-postgresql
  labels:
    {{- include "mongooseim.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  selector:
    {{- include "mongooseim.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgres
      port: {{ .Values.postgresqlBackend.port }}
      targetPort: postgres
      protocol: TCP
{{- end }}
