{{- if .Values.rabbitmqPersistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mongooseim.fullname" . }}-rabbitmq-data
  labels:
    {{- include "mongooseim.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rabbitmqPersistence.size }}
  {{- if .Values.rabbitmqPersistence.storageClass }}
  storageClassName: {{ .Values.rabbitmqPersistence.storageClass }}
  {{- end }}
{{- end }}