{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongooseim.fullname" . }}-rabbitmq
  labels:
    {{- include "mongooseim.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mongooseim.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "mongooseim.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          imagePullPolicy: {{ .Values.rabbitmq.imagePullPolicy }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.username | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.password | quote }}
            - name: RABBITMQ_DEFAULT_VHOST
              value: {{ .Values.rabbitmq.vhost | quote }}
          ports:
            - name: amqp
              containerPort: {{ .Values.rabbitmqBackend.port }}
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 35
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 15
            periodSeconds: 10
          {{- with .Values.rabbitmq.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}