{{- $enabled := false -}}
{{- if and .Values.rabbitmq .Values.rabbitmq.persistence -}}
  {{- $enabled = .Values.rabbitmq.persistence.enabled -}}
{{- else if .Values.rabbitmqPersistence -}}
  {{- $enabled = .Values.rabbitmqPersistence.enabled -}}
{{- end -}}

{{- if $enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mongooseim.fullname" . }}-rabbitmq-data
  labels:
    {{- include "mongooseim.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "1Gi" (dig "rabbitmq" "persistence" "size" (dig "rabbitmqPersistence" "size" "1Gi" .Values) .Values) }}
  {{- if and .Values.rabbitmq .Values.rabbitmq.persistence .Values.rabbitmq.persistence.storageClass }}
  storageClassName: {{ .Values.rabbitmq.persistence.storageClass }}
  {{- end }}
{{- end }}
