{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongooseim.fullname" . }}-redis
  labels:
    {{- include "mongooseim.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "mongooseim.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: {{ .Values.redisBackend.port }}
      targetPort: redis
      protocol: TCP
{{- end }}
