apiVersion: v1
kind: Service
metadata:
  name: mim-mongooseim-headless
  namespace: mim
  labels:
    app.kubernetes.io/name: mongooseim
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: mongooseim
  ports:
    - name: xmpp-client
      port: 5222
      targetPort: xmpp-client
    - name: erlang-dist
      port: 52100
      targetPort: 52100
