# Default values for mongooseim.

replicaCount: 2

image:
  repository: ghcr.io/anmol-11w/mongooseim99
  tag: "latest"
  pullPolicy: Always

mysqlBackend:
  enabled: true
  host: "127.0.0.1"
  port: 3306
  database: "mongooseim"
  username: "mongooseim"
  password: "mongooseim"

imagePullSecrets:
  - name: ghcr-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  ports:
    xmppClient:
      port: 5222
      nodePort: 30222
      protocol: TCP
    xmppServer:
      port: 5269
      nodePort: 30269
      protocol: TCP
    bosh:
      port: 5280
      nodePort: 30280
      protocol: TCP
    admin:
      port: 8888
      nodePort: 30888
      protocol: TCP
